### ISSUE TITLE
Use `program`/`end program` for main programme in Mistra

### ISSUE THREAD

**Issue by pb866** [Mistra-UEA/Mistra#5]
In str.f, we should include a `program str` / `end program str` statement to make it clearer, where the main programme starts/end. Also, it is not quite clear, why the file is called str and we should consider to rename the file main routine to `mistra`.

**Comment by JosueBock** [comment]
I agree that both changes would be fine, however much broader changes must be made in this file, so I will leave it for the moment (it will also require to update the manual, while at the moment it is consistent with the current model structure)

**Comment by rs028** [comment]
@JosueBock Can you open an issue with more information on the broader changes that need to be made to `str.f`, please? (Also in reference to point 4 of issue #2).

**Comment by JosueBock** [comment]
Main program has been explicitly identified using program / end program, and named "mistra"
See this commit : https://github.com/Mistra-UEA/Mistra/commit/7154573519c2dd92a50448a16ce4b7a2fc79bbeb
